[package]
name = "choose"
version = "1.1.2"
authors = ["Ryan Geary <rtgnj42@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
regex = "1"
lazy_static = "1"
